import React from "react";

export type ToolCategory =
  | "convert-to"
  | "convert-from"
  | "edit"
  | "organize"
  | "optimize"
  | "secure";

export interface ToolDefinition {
  id: string; // kebab-case, matches route path segment
  path: string; // e.g. '/compress'
  name: string; // Display name
  icon: string; // Emoji or SVG string
  color: string; // CSS color for icon bg tint
  bg: string; // CSS background for card
  category: ToolCategory;
  description: string; // One-line description for CommandPalette
  component: React.LazyExoticComponent<React.ComponentType>;
  keywords?: string[]; // Extra search terms for CommandPalette
}

export const TOOL_REGISTRY: ToolDefinition[] = [
  {
    id: "compress",
    path: "/compress",
    name: "Compress PDF",
    icon: "🗜️",
    color: "#00ff88",
    bg: "rgba(0,255,136,0.08)",
    category: "optimize",
    description:
      "Reduce PDF file size while preserving quality, entirely in your browser.",
    component: React.lazy(() => import("@/app/compress/CompressPdfPage")),
    keywords: ["shrink", "reduce", "size", "smaller", "optimize"],
  },
  {
    id: "ocr",
    path: "/ocr",
    name: "OCR: Images to PDF",
    icon: "🔍",
    color: "#00ccff",
    bg: "rgba(0,204,255,0.08)",
    category: "convert-to",
    description:
      "Extract text from images and create a searchable PDF document.",
    component: React.lazy(() => import("@/app/ocr/OcrPage")),
    keywords: ["scan", "image", "text recognition", "searchable"],
  },
  {
    id: "pdf-to-jpg",
    path: "/pdf-to-jpg",
    name: "PDF to JPG",
    icon: "🖼️",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    category: "convert-from",
    description:
      "Convert each PDF page into a high-resolution JPEG image file.",
    component: React.lazy(() => import("@/app/pdf-to-jpg/PdfToJpgPage")),
    keywords: ["image", "jpeg", "photo", "picture", "export"],
  },
  {
    id: "pdf-to-word",
    path: "/pdf-to-word",
    name: "PDF to Word",
    icon: "📝",
    color: "#7c3aed",
    bg: "rgba(124,58,237,0.08)",
    category: "convert-from",
    description:
      "Extract text and structure from a PDF into an editable Word document.",
    component: React.lazy(() => import("@/app/pdf-to-word/PdfToWordPage")),
    keywords: ["docx", "doc", "microsoft word", "editable"],
  },
  {
    id: "word-to-pdf",
    path: "/word-to-pdf",
    name: "Word to PDF",
    icon: "📄",
    color: "#00ff88",
    bg: "rgba(0,255,136,0.08)",
    category: "convert-to",
    description:
      "Convert a Word document into a universally readable PDF file.",
    component: React.lazy(() => import("@/app/word-to-pdf/WordToPdfPage")),
    keywords: ["docx", "doc", "microsoft word", "convert"],
  },
  {
    id: "pdf-to-excel",
    path: "/pdf-to-excel",
    name: "PDF to Excel",
    icon: "📊",
    color: "#4ade80",
    bg: "rgba(74,222,128,0.08)",
    category: "convert-from",
    description:
      "Extract tables from a PDF into an editable Excel spreadsheet.",
    component: React.lazy(() => import("@/app/pdf-to-excel/PdfToExcelPage")),
    keywords: ["xlsx", "xls", "spreadsheet", "table", "microsoft excel"],
  },
  {
    id: "excel-to-pdf",
    path: "/excel-to-pdf",
    name: "Excel to PDF",
    icon: "📋",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    category: "convert-to",
    description: "Convert an Excel spreadsheet into a fixed, print-ready PDF.",
    component: React.lazy(() => import("@/app/excel-to-pdf/ExcelToPdfPage")),
    keywords: ["xlsx", "xls", "spreadsheet", "microsoft excel", "convert"],
  },
  {
    id: "html-to-pdf",
    path: "/html-to-pdf",
    name: "HTML to PDF",
    icon: "🌐",
    color: "#00ccff",
    bg: "rgba(0,204,255,0.08)",
    category: "convert-to",
    description:
      "Convert any HTTPS webpage to a PDF, rendered locally in your browser.",
    component: React.lazy(() => import("@/app/html-to-pdf/HtmlToPdfPage")),
    keywords: ["webpage", "website", "url", "web", "convert"],
  },
  {
    id: "edit",
    path: "/edit",
    name: "Edit PDF",
    icon: "✏️",
    color: "#00ccff",
    bg: "rgba(0,204,255,0.08)",
    category: "edit",
    description:
      "Add text, delete pages, and reorder pages in any PDF document.",
    component: React.lazy(() => import("@/app/edit/EditPdfPage")),
    keywords: ["modify", "change", "text", "annotate", "write"],
  },
  {
    id: "sign",
    path: "/sign",
    name: "Sign PDF",
    icon: "✍️",
    color: "#7c3aed",
    bg: "rgba(124,58,237,0.08)",
    category: "edit",
    description:
      "Draw, type, or upload a signature and embed it into your PDF.",
    component: React.lazy(() => import("@/app/sign/SignPdfPage")),
    keywords: ["signature", "draw", "esign", "digital signature"],
  },
  {
    id: "watermark",
    path: "/watermark",
    name: "Add Watermark",
    icon: "💧",
    color: "#00ff88",
    bg: "rgba(0,255,136,0.08)",
    category: "edit",
    description: "Apply a custom text watermark to every page of your PDF.",
    component: React.lazy(() => import("@/app/watermark/WatermarkPage")),
    keywords: ["stamp", "brand", "overlay", "text", "mark"],
  },
  {
    id: "organize",
    path: "/organize",
    name: "Organize PDF",
    icon: "📑",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    category: "organize",
    description:
      "Reorder, rotate, duplicate, and delete PDF pages to reorganize documents.",
    component: React.lazy(() => import("@/app/organize/OrganizePdfPage")),
    keywords: ["reorder", "rearrange", "pages", "rotate", "delete"],
  },
  {
    id: "split",
    path: "/split",
    name: "Split PDF",
    icon: "✂️",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    category: "organize",
    description: "Extract specific pages from a PDF into a new, smaller file.",
    component: React.lazy(() => import("@/app/split/SplitPdfPage")),
    keywords: ["extract", "separate", "divide", "pages", "cut"],
  },
  {
    id: "protect",
    path: "/protect",
    name: "Protect PDF",
    icon: "🔐",
    color: "#7c3aed",
    bg: "rgba(124,58,237,0.08)",
    category: "secure",
    description:
      "Encrypt your PDF with a password to restrict unauthorized access.",
    component: React.lazy(() => import("@/app/protect/ProtectPdfPage")),
    keywords: ["password", "encrypt", "lock", "security", "restrict"],
  },
  {
    id: "searchable-pdf",
    path: "/searchable-pdf",
    name: "Searchable PDF OCR",
    icon: "🔎",
    color: "#00ccff",
    bg: "rgba(0,204,255,0.08)",
    category: "convert-from",
    description:
      "Convert scanned or image-based PDFs into searchable, selectable documents using offline OCR.",
    component: React.lazy(
      () => import("@/app/searchable-pdf/SearchablePdfPage"),
    ),
    keywords: ["ocr", "scan", "text", "selectable", "searchable"],
  },
  // ── P1 Organize tools ────────────────────────────────────────────────────
  {
    id: "merge",
    path: "/merge",
    name: "Merge PDF",
    icon: "🔗",
    color: "#00ff88",
    bg: "rgba(0,255,136,0.08)",
    category: "organize",
    description: "Combine multiple PDF files into one document in any order.",
    component: React.lazy(() => import("@/app/merge/MergePdfPage")),
    keywords: ["combine", "join", "merge", "multiple", "files"],
  },
  {
    id: "extract-pages",
    path: "/extract-pages",
    name: "Extract Pages",
    icon: "📄",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    category: "organize",
    description: "Extract specific pages from a PDF into a new document.",
    component: React.lazy(() => import("@/app/extract-pages/ExtractPagesPage")),
    keywords: ["extract", "pages", "range", "subset", "split"],
  },
  {
    id: "rotate",
    path: "/rotate",
    name: "Rotate PDF",
    icon: "🔄",
    color: "#00ccff",
    bg: "rgba(0,204,255,0.08)",
    category: "organize",
    description:
      "Rotate individual pages or all pages by 90, 180, or 270 degrees.",
    component: React.lazy(() => import("@/app/rotate/RotatePdfPage")),
    keywords: ["rotate", "turn", "orientation", "landscape", "portrait"],
  },
  {
    id: "page-numbers",
    path: "/page-numbers",
    name: "Page Numbering",
    icon: "🔢",
    color: "#7c3aed",
    bg: "rgba(124,58,237,0.08)",
    category: "edit",
    description:
      "Add page numbers with custom position, format, font, and starting number.",
    component: React.lazy(() => import("@/app/page-numbers/PageNumbersPage")),
    keywords: ["page numbers", "numbering", "footer", "header", "pagination"],
  },
  {
    id: "add-blank-pages",
    path: "/add-blank-pages",
    name: "Add Blank Pages",
    icon: "📃",
    color: "#4ade80",
    bg: "rgba(74,222,128,0.08)",
    category: "organize",
    description: "Insert a blank page at any position in your PDF.",
    component: React.lazy(
      () => import("@/app/add-blank-pages/AddBlankPagesPage"),
    ),
    keywords: ["blank", "empty", "insert", "page", "add"],
  },
  {
    id: "header-footer",
    path: "/header-footer",
    name: "Header & Footer",
    icon: "📋",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    category: "edit",
    description:
      "Add custom text headers and footers with dynamic tokens to every page.",
    component: React.lazy(() => import("@/app/header-footer/HeaderFooterPage")),
    keywords: ["header", "footer", "text", "page number", "date"],
  },
  {
    id: "crop",
    path: "/crop",
    name: "Crop PDF",
    icon: "✂️",
    color: "#00ccff",
    bg: "rgba(0,204,255,0.08)",
    category: "edit",
    description:
      "Remove margins from PDF pages by specifying crop amounts in pt or mm.",
    component: React.lazy(() => import("@/app/crop/CropPdfPage")),
    keywords: ["crop", "trim", "margins", "cut", "resize"],
  },
  {
    id: "remove-blank",
    path: "/remove-blank",
    name: "Remove Blank Pages",
    icon: "🗑️",
    color: "#ef4444",
    bg: "rgba(239,68,68,0.08)",
    category: "organize",
    description: "Automatically detect and remove blank pages from your PDF.",
    component: React.lazy(() => import("@/app/remove-blank/RemoveBlankPage")),
    keywords: ["blank", "empty", "remove", "delete", "clean"],
  },
  {
    id: "reverse-pages",
    path: "/reverse-pages",
    name: "Reverse Pages",
    icon: "🔃",
    color: "#7c3aed",
    bg: "rgba(124,58,237,0.08)",
    category: "organize",
    description: "Reverse the order of all pages or a specific page range.",
    component: React.lazy(() => import("@/app/reverse-pages/ReversePagesPage")),
    keywords: ["reverse", "flip", "order", "pages", "backwards"],
  },
  {
    id: "bookmarks",
    path: "/bookmarks",
    name: "Edit Bookmarks",
    icon: "🔖",
    color: "#00ff88",
    bg: "rgba(0,255,136,0.08)",
    category: "edit",
    description:
      "Add, rename, reorder, and nest bookmarks up to 3 levels deep.",
    component: React.lazy(() => import("@/app/bookmarks/BookmarksPage")),
    keywords: ["bookmarks", "outline", "navigation", "toc", "chapters"],
  },
  {
    id: "table-of-contents",
    path: "/table-of-contents",
    name: "Table of Contents",
    icon: "📑",
    color: "#00ccff",
    bg: "rgba(0,204,255,0.08)",
    category: "edit",
    description: "Generate a table of contents page from a bookmark list.",
    component: React.lazy(
      () => import("@/app/table-of-contents/TableOfContentsPage"),
    ),
    keywords: ["toc", "table of contents", "index", "chapters", "outline"],
  },
  {
    id: "page-labels",
    path: "/page-labels",
    name: "Add Page Labels",
    icon: "🏷️",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    category: "edit",
    description:
      "Assign Roman numerals, letters, or custom prefixes to page ranges.",
    component: React.lazy(() => import("@/app/page-labels/PageLabelsPage")),
    keywords: ["labels", "roman numerals", "prefix", "page numbers", "ranges"],
  },
  {
    id: "bates-numbering",
    path: "/bates-numbering",
    name: "Bates Numbering",
    icon: "🔢",
    color: "#7c3aed",
    bg: "rgba(124,58,237,0.08)",
    category: "edit",
    description: "Stamp sequential Bates numbers across one or more PDF files.",
    component: React.lazy(
      () => import("@/app/bates-numbering/BatesNumberingPage"),
    ),
    keywords: ["bates", "sequential", "legal", "numbering", "stamp"],
  },
  {
    id: "pdfs-to-zip",
    path: "/pdfs-to-zip",
    name: "PDFs to ZIP",
    icon: "🗜️",
    color: "#4ade80",
    bg: "rgba(74,222,128,0.08)",
    category: "organize",
    description: "Package 2–50 PDF files into a single ZIP archive.",
    component: React.lazy(() => import("@/app/pdfs-to-zip/PdfsToZipPage")),
    keywords: ["zip", "archive", "package", "bundle", "download"],
  },
  {
    id: "multi-tool",
    path: "/multi-tool",
    name: "PDF Multi Tool",
    icon: "🛠️",
    color: "#00ff88",
    bg: "rgba(0,255,136,0.08)",
    category: "organize",
    description:
      "Reorder, rotate, duplicate, delete, and add blank pages in one place.",
    component: React.lazy(() => import("@/app/multi-tool/MultiToolPage")),
    keywords: ["multi", "reorder", "organize", "pages", "all-in-one"],
  },
  // ── P1 Security tools ────────────────────────────────────────────────────
  {
    id: "repair",
    path: "/repair",
    name: "Repair PDF",
    icon: "🔧",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    category: "optimize",
    description:
      "Attempt to recover and reconstruct a corrupted or malformed PDF.",
    component: React.lazy(() => import("@/app/repair/RepairPdfPage")),
    keywords: ["repair", "fix", "corrupt", "recover", "broken"],
  },
  {
    id: "flatten",
    path: "/flatten",
    name: "Flatten PDF",
    icon: "📄",
    color: "#00ccff",
    bg: "rgba(0,204,255,0.08)",
    category: "edit",
    description:
      "Merge form fields and annotations into static content for a non-editable final version.",
    component: React.lazy(() => import("@/app/flatten/FlattenPdfPage")),
    keywords: ["flatten", "form fields", "annotations", "static", "finalize"],
  },
  {
    id: "metadata",
    path: "/metadata",
    name: "Metadata Editor",
    icon: "🏷️",
    color: "#7c3aed",
    bg: "rgba(124,58,237,0.08)",
    category: "edit",
    description:
      "View and edit PDF document properties: title, author, subject, keywords.",
    component: React.lazy(() => import("@/app/metadata/MetadataEditorPage")),
    keywords: [
      "metadata",
      "title",
      "author",
      "subject",
      "keywords",
      "properties",
    ],
  },
  {
    id: "sanitize",
    path: "/sanitize",
    name: "Sanitize PDF",
    icon: "🧹",
    color: "#ef4444",
    bg: "rgba(239,68,68,0.08)",
    category: "secure",
    description:
      "Remove metadata, annotations, JavaScript, and embedded attachments from a PDF.",
    component: React.lazy(() => import("@/app/sanitize/SanitizePdfPage")),
    keywords: [
      "sanitize",
      "clean",
      "metadata",
      "javascript",
      "attachments",
      "privacy",
    ],
  },
  {
    id: "remove-metadata",
    path: "/remove-metadata",
    name: "Remove Metadata",
    icon: "🗑️",
    color: "#ef4444",
    bg: "rgba(239,68,68,0.08)",
    category: "secure",
    description:
      "Strip all XMP and DocInfo metadata fields to remove identifying information.",
    component: React.lazy(
      () => import("@/app/remove-metadata/RemoveMetadataPage"),
    ),
    keywords: ["metadata", "remove", "strip", "privacy", "xmp", "docinfo"],
  },
  {
    id: "digital-sign",
    path: "/digital-sign",
    name: "Digital Signature",
    icon: "🔏",
    color: "#7c3aed",
    bg: "rgba(124,58,237,0.08)",
    category: "secure",
    description:
      "Embed a cryptographic digital signature using a PKCS#12 certificate (.p12/.pfx).",
    component: React.lazy(() => import("@/app/digital-sign/DigitalSignPage")),
    keywords: [
      "digital signature",
      "pkcs12",
      "certificate",
      "x509",
      "sign",
      "p12",
    ],
  },
  {
    id: "validate-signature",
    path: "/validate-signature",
    name: "Validate Signature",
    icon: "🔍",
    color: "#00ccff",
    bg: "rgba(0,204,255,0.08)",
    category: "secure",
    description:
      "Inspect all digital signature fields — view signer, date, reason, and integrity status.",
    component: React.lazy(
      () => import("@/app/validate-signature/ValidateSignaturePage"),
    ),
    keywords: [
      "validate",
      "signature",
      "verify",
      "digital",
      "certificate",
      "integrity",
    ],
  },
  // ── P1 Convert tools ─────────────────────────────────────────────────────
  {
    id: "pdf-to-png",
    path: "/pdf-to-png",
    name: "PDF to PNG",
    icon: "🖼️",
    color: "#00ccff",
    bg: "rgba(0,204,255,0.08)",
    category: "convert-from",
    description:
      "Convert each PDF page to a high-quality PNG image and download as a ZIP.",
    component: React.lazy(() => import("@/app/pdf-to-png/PdfToPngPage")),
    keywords: ["png", "image", "rasterize", "export", "picture"],
  },
  {
    id: "pdf-to-text",
    path: "/pdf-to-text",
    name: "PDF to Text",
    icon: "📝",
    color: "#7c3aed",
    bg: "rgba(124,58,237,0.08)",
    category: "convert-from",
    description:
      "Extract all text from a PDF and download as a plain .txt file.",
    component: React.lazy(() => import("@/app/pdf-to-text/PdfToTextPage")),
    keywords: ["text", "extract", "plain text", "txt", "content"],
  },
  {
    id: "pdf-to-greyscale",
    path: "/pdf-to-greyscale",
    name: "PDF to Greyscale",
    icon: "🎨",
    color: "#6b7280",
    bg: "rgba(107,114,128,0.08)",
    category: "convert-from",
    description:
      "Convert a color PDF to greyscale to reduce file size and ink usage.",
    component: React.lazy(
      () => import("@/app/pdf-to-greyscale/PdfToGreyscalePage"),
    ),
    keywords: ["greyscale", "grayscale", "black and white", "color", "convert"],
  },
  {
    id: "extract-images",
    path: "/extract-images",
    name: "Extract Images",
    icon: "🖼️",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    category: "convert-from",
    description:
      "Extract all embedded images from a PDF and download them as a ZIP archive.",
    component: React.lazy(
      () => import("@/app/extract-images/ExtractImagesPage"),
    ),
    keywords: ["extract", "images", "photos", "jpeg", "png", "embedded"],
  },
  {
    id: "pdf-to-pdfa",
    path: "/pdf-to-pdfa",
    name: "PDF to PDF/A",
    icon: "📦",
    color: "#00ff88",
    bg: "rgba(0,255,136,0.08)",
    category: "optimize",
    description:
      "Convert a PDF to the archival PDF/A format (1b or 2b) for long-term preservation.",
    component: React.lazy(() => import("@/app/pdf-to-pdfa/PdfToPdfaPage")),
    keywords: ["pdfa", "archival", "iso", "preservation", "compliance"],
  },
  {
    id: "text-to-pdf",
    path: "/text-to-pdf",
    name: "Text to PDF",
    icon: "📄",
    color: "#4ade80",
    bg: "rgba(74,222,128,0.08)",
    category: "convert-to",
    description:
      "Convert a plain text file to a formatted PDF with custom font, size, and margins.",
    component: React.lazy(() => import("@/app/text-to-pdf/TextToPdfPage")),
    keywords: ["text", "txt", "plain text", "convert", "typography"],
  },
  {
    id: "markdown-to-pdf",
    path: "/markdown-to-pdf",
    name: "Markdown to PDF",
    icon: "📋",
    color: "#00ccff",
    bg: "rgba(0,204,255,0.08)",
    category: "convert-to",
    description:
      "Convert Markdown to a styled PDF with live preview and theme selection.",
    component: React.lazy(
      () => import("@/app/markdown-to-pdf/MarkdownToPdfPage"),
    ),
    keywords: ["markdown", "md", "convert", "styled", "preview"],
  },
  {
    id: "pptx-to-pdf",
    path: "/pptx-to-pdf",
    name: "PowerPoint to PDF",
    icon: "📊",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    category: "convert-to",
    description: "Convert a PowerPoint presentation (.pptx) to a PDF document.",
    component: React.lazy(() => import("@/app/pptx-to-pdf/PptxToPdfPage")),
    keywords: [
      "powerpoint",
      "pptx",
      "ppt",
      "presentation",
      "slides",
      "convert",
    ],
  },
  {
    id: "image-to-pdf",
    path: "/image-to-pdf",
    name: "Image to PDF",
    icon: "🖼️",
    color: "#7c3aed",
    bg: "rgba(124,58,237,0.08)",
    category: "convert-to",
    description:
      "Combine multiple images (PNG, JPEG, WebP) into a single PDF document.",
    component: React.lazy(() => import("@/app/image-to-pdf/ImageToPdfPage")),
    keywords: ["image", "photo", "png", "jpeg", "combine", "convert"],
  },
  {
    id: "pdf-to-ppt",
    path: "/pdf-to-ppt",
    name: "PDF to PowerPoint",
    icon: "📊",
    color: "#ef4444",
    bg: "rgba(239,68,68,0.08)",
    category: "convert-from",
    description:
      "Rasterize each PDF page as a slide image and download as a ZIP archive.",
    component: React.lazy(() => import("@/app/pdf-to-ppt/PdfToPptPage")),
    keywords: ["powerpoint", "pptx", "slides", "presentation", "export"],
  },
  // ── P1 Edit/Annotate tools ────────────────────────────────────────────────
  {
    id: "form-filler",
    path: "/form-filler",
    name: "PDF Form Filler",
    icon: "📝",
    color: "#00ccff",
    bg: "rgba(0,204,255,0.08)",
    category: "edit",
    description:
      "Fill interactive AcroForm fields in a PDF directly in your browser.",
    component: React.lazy(() => import("@/app/form-filler/FormFillerPage")),
    keywords: ["form", "fill", "acroform", "fields", "interactive"],
  },
  {
    id: "form-builder",
    path: "/form-builder",
    name: "Create PDF Form",
    icon: "🗂️",
    color: "#7c3aed",
    bg: "rgba(124,58,237,0.08)",
    category: "edit",
    description:
      "Drag and drop form fields onto a PDF to create interactive forms.",
    component: React.lazy(() => import("@/app/form-builder/FormBuilderPage")),
    keywords: [
      "form",
      "builder",
      "create",
      "fields",
      "checkbox",
      "radio",
      "input",
    ],
  },
  {
    id: "redact",
    path: "/redact",
    name: "Redact Content",
    icon: "⬛",
    color: "#ef4444",
    bg: "rgba(239,68,68,0.08)",
    category: "secure",
    description: "Permanently black out sensitive text and regions from a PDF.",
    component: React.lazy(() => import("@/app/redact/RedactPage")),
    keywords: [
      "redact",
      "black out",
      "censor",
      "remove",
      "sensitive",
      "privacy",
    ],
  },
  {
    id: "remove-annotations",
    path: "/remove-annotations",
    name: "Remove Annotations",
    icon: "🗑️",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    category: "edit",
    description: "Strip all annotations, comments, and markup from a PDF.",
    component: React.lazy(
      () => import("@/app/remove-annotations/RemoveAnnotationsPage"),
    ),
    keywords: [
      "annotations",
      "comments",
      "markup",
      "remove",
      "clean",
      "highlights",
    ],
  },
  {
    id: "stamps",
    path: "/stamps",
    name: "Add Stamps",
    icon: "🔖",
    color: "#f59e0b",
    bg: "rgba(245,158,11,0.08)",
    category: "edit",
    description:
      "Apply built-in or custom stamps (Draft, Approved, Confidential) to PDF pages.",
    component: React.lazy(() => import("@/app/stamps/StampsPage")),
    keywords: [
      "stamp",
      "draft",
      "approved",
      "confidential",
      "watermark",
      "mark",
    ],
  },
];

/**
 * Returns all tools belonging to the given category.
 */
export function getToolsByCategory(cat: ToolCategory): ToolDefinition[] {
  return TOOL_REGISTRY.filter((tool) => tool.category === cat);
}

/**
 * Finds a tool by its id (kebab-case path segment).
 * Returns undefined if no match is found.
 */
export function findTool(id: string): ToolDefinition | undefined {
  return TOOL_REGISTRY.find((tool) => tool.id === id);
}
